/* auto-generated by NAPI-RS */
/* eslint-disable */
/** 检查文件访问权限 */
export declare function checkFileAccessSync(filePath: string): void

/** JavaScript 压缩比信息结构 */
export interface CompressionRatioJs {
  oldSize: number
  newSize: number
  patchSize: number
  ratio: number
}

export declare function diff(oldStr: string, newStr: string, patch: string): Promise<void>

/** JavaScript Diff 配置选项 */
export interface DiffOptionsJs {
  /** 压缩级别 (0-9, 默认 6) */
  compressionLevel?: number
  /** 是否启用并行处理（默认 true） */
  enableParallel?: boolean
}

export declare function diffSync(oldStr: string, newStr: string, patch: string): void

/** 生成补丁文件，支持自定义选项（异步） */
export declare function diffWithOptions(oldStr: string, newStr: string, patch: string, options: DiffOptionsJs): Promise<void>

/** 生成补丁文件，支持自定义选项并返回性能统计（同步） */
export declare function diffWithOptionsAndStatsSync(oldStr: string, newStr: string, patch: string, options: DiffOptionsJs): PerformanceStatsJs

/** 生成补丁文件，支持自定义选项（同步） */
export declare function diffWithOptionsSync(oldStr: string, newStr: string, patch: string, options: DiffOptionsJs): void

/** 生成补丁文件并返回性能统计（异步） */
export declare function diffWithStats(oldStr: string, newStr: string, patch: string): Promise<PerformanceStatsJs>

/** 生成补丁文件并返回性能统计（同步） */
export declare function diffWithStatsSync(oldStr: string, newStr: string, patch: string): PerformanceStatsJs

/** 获取压缩比信息 */
export declare function getCompressionRatioSync(oldStr: string, newStr: string, patch: string): CompressionRatioJs

/** 获取文件大小 */
export declare function getFileSizeSync(filePath: string): number

/** 获取补丁文件信息 */
export declare function getPatchInfoSync(patch: string): PatchInfoJs

export declare function patch(oldStr: string, newStr: string, patch: string): Promise<void>

/** JavaScript 补丁信息结构 */
export interface PatchInfoJs {
  size: number
  compressed: boolean
}

export declare function patchSync(oldStr: string, newStr: string, patch: string): void

/** 应用补丁文件并返回性能统计（异步） */
export declare function patchWithStats(oldStr: string, newStr: string, patch: string): Promise<PerformanceStatsJs>

/** 应用补丁文件并返回性能统计（同步） */
export declare function patchWithStatsSync(oldStr: string, newStr: string, patch: string): PerformanceStatsJs

/** JavaScript 性能统计结构 */
export interface PerformanceStatsJs {
  /** 操作耗时（毫秒） */
  elapsedMs: number
  /** 旧文件大小（字节） */
  oldSize: number
  /** 新文件大小（字节） */
  newSize: number
  /** 补丁大小（字节） */
  patchSize: number
  /** 压缩比（百分比） */
  compressionRatio: number
}

export declare function verifyPatch(oldStr: string, newStr: string, patch: string): Promise<boolean>

/** 验证补丁文件完整性 */
export declare function verifyPatchSync(oldStr: string, newStr: string, patch: string): boolean
